// Code generated by "stringer -linecomment -type=Type"; DO NOT EDIT.

package token

import "strconv"

const _Type_name = "integeridentifier'=''==''<''>''+''-''*''/''&''if''else''while''('')''{''}'';''var''int''array''of''ptr''to''char'"

var _Type_index = [...]uint8{0, 7, 17, 20, 24, 27, 30, 33, 36, 39, 42, 45, 49, 55, 62, 65, 68, 71, 74, 77, 82, 87, 94, 98, 103, 107, 113}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
