// Code generated by "stringer -linecomment -type=Type"; DO NOT EDIT.

package token

import "strconv"

const _Type_name = "TokIntegerTokIdentifier'=''==''<''>''+''-''*''/''&''if''else''while''('')''{''}'';''var''int''array''of''ptr''to''char'"

var _Type_index = [...]uint8{0, 10, 23, 26, 30, 33, 36, 39, 42, 45, 48, 51, 55, 61, 68, 71, 74, 77, 80, 83, 88, 93, 100, 104, 109, 113, 119}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
