// Code generated by "stringer -linecomment -type=BinaryOperatorType"; DO NOT EDIT.

package ast

import "strconv"

const _BinaryOperatorType_name = "'+''-''*''/''<''>''='"

var _BinaryOperatorType_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21}

func (i BinaryOperatorType) String() string {
	if i < 0 || i >= BinaryOperatorType(len(_BinaryOperatorType_index)-1) {
		return "BinaryOperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperatorType_name[_BinaryOperatorType_index[i]:_BinaryOperatorType_index[i+1]]
}
