// Code generated by "stringer -type=PrimitiveType -linecomment"; DO NOT EDIT.

package ast

import "strconv"

const _PrimitiveType_name = "'int''char'"

var _PrimitiveType_index = [...]uint8{0, 5, 11}

func (i PrimitiveType) String() string {
	if i < 0 || i >= PrimitiveType(len(_PrimitiveType_index)-1) {
		return "PrimitiveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveType_name[_PrimitiveType_index[i]:_PrimitiveType_index[i+1]]
}
