// Code generated by "stringer -type=UnaryOperatorType -linecomment"; DO NOT EDIT.

package ast

import "strconv"

const _UnaryOperatorType_name = "'*''-''&'"

var _UnaryOperatorType_index = [...]uint8{0, 3, 6, 9}

func (i UnaryOperatorType) String() string {
	if i < 0 || i >= UnaryOperatorType(len(_UnaryOperatorType_index)-1) {
		return "UnaryOperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnaryOperatorType_name[_UnaryOperatorType_index[i]:_UnaryOperatorType_index[i+1]]
}
